// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eubyijrzqmadgiqdrkmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YnlpanJ6cW1hZGdpcWRya21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTk1ODAsImV4cCI6MjA3MDkzNTU4MH0.9AWE9z14cRWOy6NEG3Nqwp3MQrUwLYQlLTV-mbSOuNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});